apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ratelimitconfigs.ratelimit.solo.io
spec:
  group: ratelimit.solo.io
  names:
    kind: RateLimitConfig
    listKind: RateLimitConfigList
    plural: ratelimitconfigs
    singular: ratelimitconfig
    shortNames:
    - rlc
    - grlc
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
