apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ingress.fullname" .}}-config
  namespace: {{ .Release.Namespace }}
data:
  envoy.yaml: |
    node:
      cluster: ingress
      id: NODE_ID_PLACE_HOLDER
    static_resources:
      clusters:
      - name: xds_cluster
        connect_timeout: 5.000s
        hosts:
        - socket_address:
            address: {{ template "gloo.fullname" . }}
            port_value: {{ .Values.gloo.port }}
        http2_protocol_options: {}
        type: STRICT_DNS
      {{- if .Values.opentracing.status }} 
      {{- if eq .Values.opentracing.status "configure" "install" }}
      - name: jaeger
        connect_timeout: 1s
        type: STRICT_DNS
        hosts:
        - socket_address:
            address: {{ template "jaeger.host" . }}
            port_value: {{ template "jaeger.port" . }}
      {{- end }}
      {{- end }}
      {{- if .Values.metrics.status }}
      {{- if eq .Values.metrics.status "statsd" "prometheus" "all" }}
      - name: statsd
        connect_timeout: 1s
        type: STRICT_DNS
        hosts:
        - socket_address:
            address: {{ template "statsd.host" . }}
            port_value: {{ template "statsd.port" . }}
      {{- end }}
      {{- end }}
    dynamic_resources:
      ads_config:
        api_type: GRPC
        cluster_names:
        - xds_cluster
      cds_config:
        ads: {}
      lds_config:
        ads: {}
    admin:
      access_log_path: /dev/null
      address:
        socket_address:
          address: 0.0.0.0
          port_value: {{ .Values.ingress.adminPort }}
    {{- if .Values.metrics.status }}
    {{- if eq .Values.metrics.status "statsd" "prometheus" "all" }}
    stats_sinks:
    - name: envoy.statsd
      config:
        tcp_cluster_name: statsd
    {{- end }}
    {{- end }}
