baseURL = "https://gloo.solo.io/"
languageCode = "en-us"
title = "Gloo Docs"
# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn" # https://learn.netlify.com

contentDir = "docs"
# staticDir = "docs/static"
publishDir = "site"

googleAnalytics = "UA-101654320-1"
ignoreFiles = [ "README.md$"]

# For search functionality
[outputs]
home = [ "HTML", "JSON"]

[params]
  # Prefix URL to edit current page. Will display an "Edit this page" button on top right hand corner of every page. 
  # Useful to give opportunity to people to create merge request for your doc.
  # See the config.toml file from this documentation site to have an example.
  # editURL = "https://github.com/solo-io/gloo/tree/master/docs/"
  
  # Author of the site, will be used in meta information
  author = ""
  # Description of the site, will be used in meta information
  description = ""
  # Shows a checkmark for visited pages on the menu
  showVisitedLinks = false
  # Disable search function. It will hide search bar
  disableSearch = false
  # Javascript and CSS cache are automatically busted when new version of site is generated. 
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
  disableAssetsBusting = false
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = false
  # A title for shortcuts in menu is set by default. Set this to true to disable it. 
  disableShortcutsTitle = false
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = false
  # Hide breadcrumbs in the header and only show the current page title
  disableBreadcrumb = true
  # Hide Next and Previous page buttons normally displayed full height beside content
  disableNextPrev = false
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby = "weight"
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Github Repo"
identifier = "ds"
url = "https://github.com/solo-io/gloo"
weight = 10

 [[menu.shortcuts]]
 name = "<i class='fas fa-bookmark'></i> Solo.io Homepage"
 identifier = "soloio"
 url = "https://solo.io/"
 weight = 20

# [[menu.shortcuts]]
# name = "<i class='fas fa-bullhorn'></i> Credits"
# url = "/credits"
# weight = 30
