[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  version = "0.6.11"
  name = "github.com/envoyproxy/go-control-plane"
  source = "github.com/yuval-k/go-control-plane"

[[constraint]]
  version = "1.1.1"
  name = "github.com/gogo/protobuf"

[[override]]
  branch = "master"
  name = "k8s.io/api"

[[override]]
  version = "1.2.0"
  name = "github.com/golang/protobuf"

[[constraint]]
  name = "github.com/solo-io/envoy-operator"
  version = "0.1.0"

[[constraint]]
  name = "github.com/solo-io/solo-kit"
  version = "0.9.0"

[[constraint]]
  name = "github.com/solo-io/go-utils"
  version = "0.8.4"

[[constraint]]
  name = "github.com/hashicorp/consul"
  revision = "eba25a143821cec25bdb48fe64dd7b7a6152d01d"

# go versioning story not ideal, so we have to pin serf to the version consul expects
[[override]]
  name = "github.com/hashicorp/serf"
  revision = "19bbd39e421bdf3559d5025fb2c760f5ffa56233"

[[constraint]]
  name = "github.com/solo-io/go-checkpoint"
  version = "0.0.4"

# make sure all kubernetes code is the same version.
# when updating, update all in the same time.

[[override]]
  name = "k8s.io/kubernetes"
  version = "=v1.13.1"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/helm"
  version = "v2.12.3"

[[override]]
  name = "github.com/lyft/protoc-gen-validate"
  version = "0.0.6"
  source = "github.com/envoyproxy/protoc-gen-validate"
