site_name: gloo
pages:
    - Index: index.md
    - About gloo:
      - Introduction: introduction/introduction.md
      - Concepts: introduction/concepts.md
      - Architecture: introduction/architecture.md
    - v1 API reference:
      - Overview: v1/overview.md
      - Upstreams: v1/upstream.md
      - Virtual Hosts: v1/virtualhost.md
      - Metadata: v1/metadata.md
      - Status: v1/status.md
repo_url: https://github.com/solo-io/gloo/
site_author: gloo Project Authors
copyright: Â© Copyright 2018, solo.io Inc.
#google_analytics: ['todo']
theme: readthedocs
extra_css: [extra.css]
extra:
    version: 1.0