site_name: Gloo
pages:
- Index: index.md
- Installation:
  - Installing on Kubernetes: installation/kubernetes.md
- Getting Started:
  - Kubernetes:
    - Basic Routing: getting_started/kubernetes/1.md
    - Function Routing: getting_started/kubernetes/2.md
- CLI reference: cli.md
- v1 API reference:
  - Overview: v1/gloo.solo.io.project.sk.md
  - Upstreams: v1/upstream.proto.sk.md
  - VirtualServices: v1/virtual_service.proto.sk.md
  - Secrets: v1/secret.proto.sk.md
  - Artifacts: v1/artifact.proto.sk.md
  - Plugins:
    - Plugin Overview: v1/plugins.proto.sk.md
    - Transformation: v1/plugins/transformation/transformation.proto.sk.md
    - Transformation Parameters: v1/plugins/transformation/parameters.proto.sk.md
    - Transformation Prefix Rewrite: v1/plugins/transformation/prefix_rewrite.proto.sk.md
    - Service Spec: v1/plugins/service_spec.proto.sk.md
    - Aws: v1/plugins/aws/aws.proto.sk.md
    - Azure: v1/plugins/azure/azure.proto.sk.md
    - Rest: v1/plugins/rest/rest.proto.sk.md
    - Static: v1/plugins/static/static.proto.sk.md
    - Consul: v1/plugins/consul/consul.proto.sk.md
    - Kubernetes: v1/plugins/kubernetes/kubernetes.proto.sk.md
    - Sqoop: v1/plugins/sqoop/sqoop.proto.sk.md
    - Rate Limit: v1/plugins/ratelimit/ratelimit.proto.sk.md
    - gRPC: v1/plugins/grpc/grpc.proto.sk.md
    - Fault Injection: v1/plugins/faultinjection/fault.proto.sk.md
  - Core:
    - Metadata: v1/core/metadata.proto.sk.md
    - Status: v1/core/status.proto.sk.md
    - ResourceRef: v1/core/ref.proto.sk.md
  - Advanced:
    - Settings: v1/settings.proto.sk.md
    - Gateways: v1/gateway.proto.sk.md
    - Proxies: v1/proxy.proto.sk.md

repo_url: https://github.com/solo-io/gloo/
site_author: Gloo Project Authors
copyright: Â© Copyright 2018, solo.io Inc.
google_analytics: ['UA-101654320-1', 'gloo.solo.io'] # TODO (rick): UA-... copied from glooE
theme:
  name: 'material'
  favicon: 'img/favicon.ico'
extra_css: [extra.css]
extra:
  version: 0.1.1
