site_name: gloo
pages:
    - Index: index.md
    - About gloo:
      - Introduction: introduction/introduction.md
      - Concepts: introduction/concepts.md
      - Architecture: introduction/architecture.md
    - Installation:
      - Installing on Kubernetes: installation/kubernetes.md
      - Installing on OpenShift: installation/openshift.md
#      - Installing on Local Docker: installation/docker.md
    - Getting Started:
      - Kubernetes:
        - Basic Routing: getting_started/kubernetes/1.md
        - Function Routing: getting_started/kubernetes/2.md
      - OpenShift:
        - Basic Routing: getting_started/openshift/1.md
        - Function Routing: getting_started/openshift/2.md
      - AWS:
        - Basic Lambda with Gloo: getting_started/aws/lambda.md
    - Tutorials:
#      - Extending Microservices with Serverless: tutorials/extend_microservice.md
      - Refactoring Monoliths with Microservices and Serverless: tutorials/refactor_monolith.md
      - Sourcing NATS Messages from HTTP Requests: tutorials/source_events_from_github.md
    - Plugins:
      - AWS Lambda Plugin: plugins/aws.md
      - Kubernetes Plugin: plugins/kubernetes.md
      - Request Transformation Plugin: plugins/request_transformation.md
      - External Service Plugin: plugins/service.md
    - thetool:
      - Install: thetool/install.md
      - Quick Start: thetool/quickstart.md
      - Building Custom Gloo: thetool/custom.md
#      - Getting Started on Local Docker: installation/docker.md
    - Advanced:
      - Bootstrap Options: advanced/bootstrap_options.md
    - v1 API reference:
#      - Overview: v1/overview.md
      - Upstreams: v1/upstream.md
      - Virtual Hosts: v1/virtualhost.md
      - Metadata: v1/metadata.md
      - Status: v1/status.md
repo_url: https://github.com/solo-io/gloo/
site_author: gloo Project Authors
copyright: Â© Copyright 2018, solo.io Inc.
google_analytics: ['UA-101654320-1', 'gloo.solo.io']
theme:
  name: 'rtd-dropdown'
extra_css: [extra.css]
extra:
    version: 0.1.1