site_name: Gloo
strict: true
nav:
- Index: index.md
- About:
  - Architecture: introduction/architecture.md
  - Concepts: introduction/concepts.md
  - Developer Guide: dev/README.md
- Installation:
  - Installing on Kubernetes: installation/kubernetes.md
- Getting Started:
  - Kubernetes:
    - Basic Routing: getting_started/kubernetes/basic_routing.md
    - Routing to external APIs: getting_started/kubernetes/external_api_routing.md
    - Function Routing: getting_started/kubernetes/function_routing.md
- CLI reference: cli/README.md
- v1 API reference:
  - Overview: v1/gloo.solo.io.project.sk.md
  - Upstreams: v1/github.com/solo-io/gloo/projects/gloo/api/v1/upstream.proto.sk.md
  - VirtualServices: v1/github.com/solo-io/gloo/projects/gateway/api/v1/virtual_service.proto.sk.md
  - Secrets: v1/github.com/solo-io/gloo/projects/gloo/api/v1/secret.proto.sk.md
  - Artifacts: v1/github.com/solo-io/gloo/projects/gloo/api/v1/artifact.proto.sk.md
  - Plugins:
    - Plugin Overview: v1/github.com/solo-io/gloo/projects/gloo/api/v1/plugins.proto.sk.md
    - Transformation: v1/github.com/solo-io/gloo/projects/gloo/api/v1/plugins/transformation/transformation.proto.sk.md
    - Transformation Parameters: v1/github.com/solo-io/gloo/projects/gloo/api/v1/plugins/transformation/parameters.proto.sk.md
    - Transformation Prefix Rewrite: v1/github.com/solo-io/gloo/projects/gloo/api/v1/plugins/transformation/prefix_rewrite.proto.sk.md
    - Service Spec: v1/github.com/solo-io/gloo/projects/gloo/api/v1/plugins/service_spec.proto.sk.md
    - Aws: v1/github.com/solo-io/gloo/projects/gloo/api/v1/plugins/aws/aws.proto.sk.md
    - Azure: v1/github.com/solo-io/gloo/projects/gloo/api/v1/plugins/azure/azure.proto.sk.md
    - Rest: v1/github.com/solo-io/gloo/projects/gloo/api/v1/plugins/rest/rest.proto.sk.md
    - Static: v1/github.com/solo-io/gloo/projects/gloo/api/v1/plugins/static/static.proto.sk.md
    - Consul: v1/github.com/solo-io/gloo/projects/gloo/api/v1/plugins/consul/consul.proto.sk.md
    - Kubernetes: v1/github.com/solo-io/gloo/projects/gloo/api/v1/plugins/kubernetes/kubernetes.proto.sk.md
    - gRPC: v1/github.com/solo-io/gloo/projects/gloo/api/v1/plugins/grpc/grpc.proto.sk.md
    - Fault Injection: v1/github.com/solo-io/gloo/projects/gloo/api/v1/plugins/faultinjection/fault.proto.sk.md
  - Core:
    - Metadata: v1/github.com/solo-io/solo-kit/api/v1/metadata.proto.sk.md
    - Status: v1/github.com/solo-io/solo-kit/api/v1/status.proto.sk.md
    - ResourceRef: v1/github.com/solo-io/solo-kit/api/v1/ref.proto.sk.md
  - Advanced:
    - Settings: v1/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
    - Gateways: v1/github.com/solo-io/gloo/projects/gateway/api/v1/gateway.proto.sk.md
    - Proxies: v1/github.com/solo-io/gloo/projects/gloo/api/v1/proxy.proto.sk.md
site_author: solo.io
copyright: Â© Copyright 2018, solo.io Inc.
repo_url: https://github.com/solo-io/gloo/
edit_uri: ""
google_analytics: ['UA-101654320-1', 'gloo.solo.io'] # TODO (rick): UA-... copied from glooE
theme:
  name: 'mkdocs'
  favicon: 'img/favicon.ico'
extra_css: [extra.css]
extra:
  version: 0.1.1
plugins:
  - search


