site_name: gloo
pages:
    - Index: index.md
    - About gloo:
      - Introduction: introduction/introduction.md
      - Concepts: introduction/concepts.md
      - Architecture: introduction/architecture.md
    - Installation:
      - Installing on Kubernetes: installation/kubernetes.md
#      - Installing on Local Docker: installation/docker.md
    - Getting Started:
      - AWS:
        - Basic Lambda with Gloo: getting_started/aws/lambda.md
#        - Petstore Demo with Gloo: example/aws/lambda.md
      - Kubernetes:
        - Part 1 - Basic Routing: getting_started/kubernetes/1.md
        - Part 2 - Function Routing: getting_started/kubernetes/2.md
      - Demos:
        - Composing Apps with Gloo: getting_started/demos/composing_apps_with_gloo.md
    - thetool:
      - Install: thetool/install.md
      - Quick Start: thetool/quickstart.md
      - Building Custom Gloo: thetool/custom.md
#      - Getting Started on Local Docker: installation/docker.md
    - Plugins:
      - AWS Lambda Plugin: plugins/aws.md
      - Kubernetes Plugin: plugins/kubernetes.md
      - Request Transformation Plugin: plugins/request_transformation.md
      - External Service Plugin: plugins/service.md
    - Advanced:
      - Bootstrap Options: advanced/bootstrap_options.md
    - v1 API reference:
#      - Overview: v1/overview.md
      - Upstreams: v1/upstream.md
      - Virtual Hosts: v1/virtualhost.md
      - Metadata: v1/metadata.md
      - Status: v1/status.md
repo_url: https://github.com/solo-io/gloo/
site_author: gloo Project Authors
copyright: Â© Copyright 2018, solo.io Inc.
#google_analytics: ['todo']
theme:
  name: 'rtd-dropdown'
extra_css: [extra.css]
extra:
    version: 0.1.1