version: '3'

services:

  # consul
  # note: this consul instance is being run in dev mode
  # and should not be used in production
  consul:
    image: "consul:${CONSUL_VERSION:-1.10.0}"
    working_dir: /
    command:
      - "agent"
      - "-dev"
      - "--client=0.0.0.0"
      - "--node=consul-dev"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    restart: always

  # vault
  # note: this vault instance is being run in dev mode
  # and should not be used in production
  vault:
    image: "vault:${VAULT_VERSION:-1.6.0}"
    working_dir: /
    command:
      - "server"
      - "-dev"
      - "-dev-root-token-id=root"
      - "-dev-listen-address=0.0.0.0:8200"
    ports:
      - "8200:8200"
    restart: always

  # example application, the swagger petstore
  petstore:
    image: ${PETSTORE_REPO:-quay.io/solo-io}/petstore:v1
    ports:
    - "8090:8080"
    restart: always

  # Gloo components
  gloo:
    image: ${GLOO_REPO:-quay.io/solo-io}/gloo:${GLOO_VERSION:-1.10.0}
    working_dir: /
    command:
    - "--dir=/data/"
    volumes:
    - ./data:/data/
    ports:
    - "9977:9977"
    restart: always

  discovery:
    image: ${GLOO_REPO:-quay.io/solo-io}/discovery:${GLOO_VERSION:-1.14.6}
    working_dir: /
    command:
    - "--dir=/data/"
    volumes:
    - ./data:/data/
    restart: always

  gateway-proxy:
    image: ${GLOO_REPO:-quay.io/solo-io}/gloo-envoy-wrapper:${GLOO_VERSION:-1.14.6}
    entrypoint: ["envoy"]
    command: ["-c", "/config/envoy.yaml", "--disable-hot-restart"]
    volumes:
    - ./data/envoy-config.yaml:/config/envoy.yaml:ro
    ports:
    - "8080:8080"
    - "8443:8443"
    - "19000:19000"
    restart: always
