version: '3'
services:

  control-plane:
    image: "soloio/control-plane:0.4.0"
    working_dir: /config/
    command:
    - "--storage.type=file"
    - "--storage.refreshrate=1s"
    - "--secrets.type=file"
    - "--secrets.refreshrate=1s"
    - "--files.type=file"
    - "--files.refreshrate=1s"
    - "--xds.port=8081"
    volumes:
    - ./:/config/
    ports:
    - "8081:8081"

  ingress:
    image: soloio/envoy:0.4.0
    entrypoint: ["envoy"]
    command: ["-c", "/config/envoy.yaml", "--v2-config-only"]
    volumes:
    - ./envoy-config.yaml:/config/envoy.yaml:ro
    ports:
    - "8080:8080"
    - "8443:8443"
    - "19000:19000"

  function-discovery:
    image: "soloio/function-discovery:0.4.0"
    working_dir: /config/
    command:
    - "--storage.type=file"
    - "--storage.refreshrate=1s"
    - "--secrets.type=file"
    - "--secrets.refreshrate=1s"
    - "--files.type=file"
    - "--files.refreshrate=1s"
    volumes:
    - ./:/config/

