{{- if .Values.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    app: gloo
    {{- if .Values.global.istioIntegration.labelInstallNamespace }}
      {{- if .Values.global.istioIntegration.istioSidecarRevTag }}
    istio.io/rev: {{ .Values.global.istioIntegration.istioSidecarRevTag }}
      {{- else }}
    istio-injection: enabled
      {{- end }}
    {{- end}}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1" # Ensure that this is always the first hook triggered
{{- end}}