{{- $image := .Values.gloo.deployment.image }}
{{- $statsConfig := coalesce .Values.gloo.deployment.stats .Values.global.glooStats -}}
{{- if .Values.global  }}
{{- $image = merge .Values.gloo.deployment.image .Values.global.image }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gloo
    gloo: gloo
  name: gloo
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.gloo.deployment.replicas }}
  selector:
    matchLabels:
      gloo: gloo
  template:
    metadata:
      labels:
        gloo: gloo
      {{- if $statsConfig.enabled }}
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9091"
        prometheus.io/scrape: "true"
      {{- end}}
    spec:
      serviceAccountName: gloo
      volumes:
{{- if .Values.global.glooMtls.enabled }}
      - name: gloo-mtls-certs
        secret:
          defaultMode: 420
          secretName: gloo-mtls-certs
      - name: envoy-sidecar-config
        configMap:
          name: envoy-sidecar-config
{{- end }}
      - name: labels-volume
        downwardAPI:
          items:
            - path: "labels"
              fieldRef:
                fieldPath: metadata.labels
      containers:
{{- if .Values.global.glooMtls.enabled }}
      {{- $sdsImage := merge .Values.global.glooMtls.sds.image .Values.global.image }}
      {{- $envoyImage := merge .Values.global.glooMtls.envoy.image .Values.global.image}}
      - env:
        - name: ENVOY_SIDECAR
          value: "true"
        name: envoy-sidecar
        image: {{ template "gloo.image" $envoyImage }}
        imagePullPolicy: {{ $envoyImage.pullPolicy }}
        ports:
        - containerPort: {{ .Values.gloo.deployment.xdsPort }}
          name: grpc-xds
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: {{ .Values.gloo.deployment.xdsPort }}
          initialDelaySeconds: 1
          periodSeconds: 2
          failureThreshold: 10
        volumeMounts:
        - mountPath: /etc/envoy
          name: envoy-sidecar-config
        - mountPath: /etc/envoy/ssl
          name: gloo-mtls-certs
          readOnly: true
      - name: sds
        image: {{ template "gloo.image" $sdsImage }}
        imagePullPolicy: {{ $sdsImage.pullPolicy }}
        volumeMounts:
        - mountPath: /etc/envoy/ssl
          name: gloo-mtls-certs
          readOnly: true
{{- end }}
      - image: {{template "gloo.image" $image }}
        imagePullPolicy: {{ $image.pullPolicy }}
        name: gloo
{{- if .Values.gloo.deployment.resources }}
        resources:
{{ toYaml .Values.gloo.deployment.resources | indent 10}}
{{- else}}
        resources:
          requests:
            cpu: 500m
            memory: 256Mi
{{- end}}
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          {{- /* set floatingUserId to true in the helm install to let the pod be assigned a dynamic user ID */ -}}
          {{- /* see https://github.com/helm/helm/issues/1707#issuecomment-520357573 */ -}}
          {{- /* the user id may be set quite high -- openshift wants userids that may get printed as scientific notation */}}
          {{- if not .Values.gloo.deployment.floatingUserId }}
          runAsUser: {{ printf "%.0f" .Values.gloo.deployment.runAsUser -}}
          {{- end }}
          capabilities:
            drop:
            - ALL
        ports:
{{- if not .Values.global.glooMtls.enabled }}
        - containerPort: {{ .Values.gloo.deployment.xdsPort }}
          name: grpc-xds
          protocol: TCP
{{- end }}
        - containerPort: {{ .Values.gloo.deployment.validationPort }}
          name: grpc-validation
          protocol: TCP
        - containerPort: 9979
          name: wasm-cache
          protocol: TCP
        volumeMounts:
        - name: labels-volume
          mountPath: /etc/gloo
          readOnly: true
        env:
{{- if .Values.gloo.deployment.customEnv }}
{{ toYaml .Values.gloo.deployment.customEnv | indent 10 }}
{{- end }}
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        {{- if $statsConfig.enabled }}
          - name: START_STATS_SERVER
            value: "true"
        {{- end}}
        {{- if .Values.gloo.deployment.disableUsageStatistics }}
          - name: DISABLE_USAGE_REPORTING
            value: "true"
        {{- end}}
        {{- if .Values.global.wasm.enabled }}
          - name: WASM_ENABLED
            value: "true"
        {{- end }}
{{- if not .Values.global.glooMtls.enabled }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.gloo.deployment.xdsPort }}
          initialDelaySeconds: 1
          periodSeconds: 2
          failureThreshold: 10
{{- end }}
      {{- if $image.pullSecret }}
      imagePullSecrets:
        - name: {{ $image.pullSecret }}
      {{- end}}
