{{- if .Values.ingress.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gloo
    gloo: ingress-proxy
    installationId: {{ include "gloo.installationId" . }}
  name: ingress-proxy
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ .Values.ingressProxy.deployment.httpPort }}
    protocol: TCP
    name: http
  - port: {{ .Values.ingressProxy.deployment.httpsPort }}
    protocol: TCP
    name: https
  selector:
    gloo: ingress-proxy
    installationId: {{ include "gloo.installationId" . }}
  type: LoadBalancer


{{- end }}