{{- if .Values.global.glooRbac.create }}
{{- if .Values.gateway.enabled }}
---
kind: {{ include "gloo.roleKind" . }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: kube-resource-watcher{{ include "gloo.rbacNameSuffix" . }}
{{- if .Values.global.glooRbac.namespaced }}
    namespace: {{ .Release.Namespace }}
{{- end }}
    labels:
        app: gloo
        gloo: rbac
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - secrets
  - endpoints
  - configmaps
  - namespaces
  verbs:
  - get
  - list
  - watch
---
kind: {{ include "gloo.roleKind" . }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: gloo-upstream-mutator{{ include "gloo.rbacNameSuffix" . }}
{{- if .Values.global.glooRbac.namespaced }}
    namespace: {{ .Release.Namespace }}
{{- end }}
    labels:
        app: gloo
        gloo: rbac
rules:
- apiGroups:
  - gloo.solo.io
  resources:
  - upstreams
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
---
kind: {{ include "gloo.roleKind" . }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: gloo-resource-reader{{ include "gloo.rbacNameSuffix" . }}
{{- if .Values.global.glooRbac.namespaced }}
    namespace: {{ .Release.Namespace }}
{{- end }}
    labels:
        app: gloo
        gloo: rbac
rules:
- apiGroups:
  - gloo.solo.io
  resources:
  - upstreams
  - upstreamgroups
  - proxies
  verbs:
  - get
  - list
  - watch
  - update # needed for status updates
- apiGroups:
  - enterprise.gloo.solo.io
  resources:
  - authconfigs
  verbs:
  - get
  - list
  - watch
  - update # needed for status updates
- apiGroups:
  - ratelimit.solo.io
  resources:
  - ratelimitconfigs
  - ratelimitconfigs/status
  verbs:
  - get
  - list
  - watch
  - update # needed for status updates
- apiGroups:
  - graphql.gloo.solo.io
  resources:
  - graphqlapis
  - graphqlapis/status
  verbs:
  - get
  - list
  - watch
  - update # needed for status updates
- apiGroups:
  - ""
  resources:
  - configmaps # used for recording envoy metrics
  verbs:
  - get
  - update
---
kind: {{ include "gloo.roleKind" . }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: settings-user{{ include "gloo.rbacNameSuffix" . }}
{{- if .Values.global.glooRbac.namespaced }}
    namespace: {{ .Release.Namespace }}
{{- end }}
    labels:
        app: gloo
        gloo: rbac
rules:
- apiGroups:
  - gloo.solo.io
  resources:
  - settings
  verbs:
  - get
  - list
  - watch
  - create
---
kind: {{ include "gloo.roleKind" . }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: gloo-resource-mutator{{ include "gloo.rbacNameSuffix" . }}
{{- if .Values.global.glooRbac.namespaced }}
    namespace: {{ .Release.Namespace }}
{{- end }}
    labels:
        app: gloo
        gloo: rbac
rules:
- apiGroups:
  - gloo.solo.io
  resources:
  - proxies
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
---
kind: {{ include "gloo.roleKind" . }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: gateway-resource-reader{{ include "gloo.rbacNameSuffix" . }}
{{- if .Values.global.glooRbac.namespaced }}
    namespace: {{ .Release.Namespace }}
{{- end }}
    labels:
        app: gloo
        gloo: rbac
rules:
- apiGroups:
  - gateway.solo.io
  resources:
  - gateways
  - httpgateways
  - virtualservices
  - routetables
  - virtualhostoptions
  - routeoptions
  verbs:
  - get
  - list
  - watch
  - update # needed for status updates
- apiGroups:
  - gateway.solo.io
  resources:
  - gateways
  verbs:
  - create # needed for creating the default gateways
---
kind: {{ include "gloo.roleKind" . }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-graphqlapi-mutator{{ include "gloo.rbacNameSuffix" . }}
  {{- if .Values.global.glooRbac.namespaced }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    app: gloo
    gloo: rbac
rules:
- apiGroups:
  - graphql.gloo.solo.io
  resources:
  - graphqlapis
  - graphqlapis/status
  verbs:
  - get
  - list
  - watch
  - update
  - create
{{- end -}}
{{- end -}}
