{{- if .Values.global.glooRbac.create }}
{{- if .Values.gateway.enabled }}
---
kind: {{ include "gloo.roleKind" . }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: kube-resource-watcher{{ include "gloo.rbacNameSuffix" . }}
{{- if .Values.global.glooRbac.namespaced }}
    namespace: {{ .Release.Namespace }}
{{- end }}
    labels:
        app: gloo
        gloo: rbac
rules:
- apiGroups: [""]
  resources: ["pods", "services", "secrets", "endpoints", "configmaps", "namespaces"]
  verbs: ["get", "list", "watch"]
---
kind: {{ include "gloo.roleKind" . }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: gloo-upstream-mutator{{ include "gloo.rbacNameSuffix" . }}
{{- if .Values.global.glooRbac.namespaced }}
    namespace: {{ .Release.Namespace }}
{{- end }}
    labels:
        app: gloo
        gloo: rbac
rules:
- apiGroups: ["gloo.solo.io"]
  resources: ["upstreams"]
  # update is needed for status updates
  verbs: ["get", "list", "watch", "create", "update", "delete"]
---
kind: {{ include "gloo.roleKind" . }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: gloo-resource-reader{{ include "gloo.rbacNameSuffix" . }}
{{- if .Values.global.glooRbac.namespaced }}
    namespace: {{ .Release.Namespace }}
{{- end }}
    labels:
        app: gloo
        gloo: rbac
rules:
- apiGroups: ["gloo.solo.io", "enterprise.gloo.solo.io"]
  resources: ["upstreams","upstreamgroups", "proxies", "authconfigs"]
  # update is needed for status updates
  verbs: ["get", "list", "watch", "update"]
- apiGroups: [""] # get/update on configmaps for recording envoy metrics
  resources: ["configmaps"]
  verbs: ["get", "update"]
---
kind: {{ include "gloo.roleKind" . }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: settings-user{{ include "gloo.rbacNameSuffix" . }}
{{- if .Values.global.glooRbac.namespaced }}
    namespace: {{ .Release.Namespace }}
{{- end }}
    labels:
        app: gloo
        gloo: rbac
rules:
- apiGroups: ["gloo.solo.io"]
  resources: ["settings"]
  # update is needed for status updates
  verbs: ["get", "list", "watch", "create"]
---
kind: {{ include "gloo.roleKind" . }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: gloo-resource-mutator{{ include "gloo.rbacNameSuffix" . }}
{{- if .Values.global.glooRbac.namespaced }}
    namespace: {{ .Release.Namespace }}
{{- end }}
    labels:
        app: gloo
        gloo: rbac
rules:
- apiGroups: ["gloo.solo.io"]
  resources: ["proxies"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
---
kind: {{ include "gloo.roleKind" . }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: gateway-resource-reader{{ include "gloo.rbacNameSuffix" . }}
{{- if .Values.global.glooRbac.namespaced }}
    namespace: {{ .Release.Namespace }}
{{- end }}
    labels:
        app: gloo
        gloo: rbac
rules:
- apiGroups: ["gateway.solo.io"]
  resources: ["virtualservices", "routetables"]
  # update is needed for status updates
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["gateway.solo.io"]
  resources: ["gateways"]
  # update is needed for status updates, create for creating the default ones.
  verbs: ["get", "list", "watch", "create", "update"]

{{- end -}}
{{- end -}}
