{{- if .Values.global.glooRbac.create }}

{{- if .Values.settings.integrations.knative.enabled }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-role-knative{{ include "gloo.rbacNameSuffix" . }}
  labels:
    app: gloo
    gloo: rbac
rules:
- apiGroups: [""]
  resources: ["pods", "services", "secrets", "endpoints", "configmaps"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "create"]
- apiGroups: ["gloo.solo.io", "enterprise.gloo.solo.io"]
  resources: ["settings", "upstreams","upstreamgroups", "proxies","virtualservices", "routetables", "authconfigs"]
  verbs: ["*"]
- apiGroups: ["ratelimit.solo.io"]
  resources: ["ratelimitconfigs","ratelimitconfigs/status"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["graphql.gloo.solo.io"]
  resources: ["graphqlapis", "graphqlapis/status"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["networking.internal.knative.dev"]
  resources: ["clusteringresses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.internal.knative.dev"]
  resources: ["clusteringresses/status"]
  verbs: ["update"]
- apiGroups: ["networking.internal.knative.dev"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.internal.knative.dev"]
  resources: ["ingresses/status"]
  verbs: ["update"]
{{- end -}}

{{- end -}}
