{{- if .Values.global.glooRbac.create }}
{{- if .Values.gateway.enabled }}
---
kind: {{ include "gloo.roleKind" . }}Binding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-resource-watcher-binding{{ include "gloo.rbacNameSuffix" . }}
{{- if .Values.global.glooRbac.namespaced }}
  namespace: {{ .Release.Namespace }}
{{- end }}
  labels:
    app: gloo
    gloo: rbac
subjects:
- kind: ServiceAccount
  name: gloo
  namespace: {{ .Release.Namespace }}
{{- if .Values.discovery.enabled }}
- kind: ServiceAccount
  name: discovery
  namespace: {{ .Release.Namespace }}
{{- end }}
roleRef:
  kind: {{ include "gloo.roleKind" . }}
  name: kube-resource-watcher{{ include "gloo.rbacNameSuffix" . }}
  apiGroup: rbac.authorization.k8s.io
---
kind: {{ include "gloo.roleKind" . }}Binding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-upstream-mutator-binding{{ include "gloo.rbacNameSuffix" . }}
{{- if .Values.global.glooRbac.namespaced }}
  namespace: {{ .Release.Namespace }}
{{- end }}
  labels:
    app: gloo
    gloo: rbac
subjects:
{{- if .Values.discovery.enabled }}
- kind: ServiceAccount
  name: discovery
  namespace: {{ .Release.Namespace }}
{{- else }}
  []
{{- end}}
roleRef:
  kind: {{ include "gloo.roleKind" . }}
  name: gloo-upstream-mutator{{ include "gloo.rbacNameSuffix" . }}
  apiGroup: rbac.authorization.k8s.io
---
kind: {{ include "gloo.roleKind" . }}Binding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-resource-reader-binding{{ include "gloo.rbacNameSuffix" . }}
{{- if .Values.global.glooRbac.namespaced }}
  namespace: {{ .Release.Namespace }}
{{- end }}
  labels:
    app: gloo
    gloo: rbac
subjects:
- kind: ServiceAccount
  name: gloo
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: {{ include "gloo.roleKind" . }}
  name: gloo-resource-reader{{ include "gloo.rbacNameSuffix" . }}
  apiGroup: rbac.authorization.k8s.io
---
kind: {{ include "gloo.roleKind" . }}Binding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: settings-user-binding{{ include "gloo.rbacNameSuffix" . }}
{{- if .Values.global.glooRbac.namespaced }}
  namespace: {{ .Release.Namespace }}
{{- end }}
  labels:
    app: gloo
    gloo: rbac
subjects:
- kind: ServiceAccount
  name: gloo
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: gateway
  namespace: {{ .Release.Namespace }}
{{- if .Values.discovery.enabled }}
- kind: ServiceAccount
  name: discovery
  namespace: {{ .Release.Namespace }}
{{- end}}
roleRef:
  kind: {{ include "gloo.roleKind" . }}
  name: settings-user{{ include "gloo.rbacNameSuffix" . }}
  apiGroup: rbac.authorization.k8s.io
---
kind: {{ include "gloo.roleKind" . }}Binding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-resource-mutator-binding{{ include "gloo.rbacNameSuffix" . }}
{{- if .Values.global.glooRbac.namespaced }}
  namespace: {{ .Release.Namespace }}
{{- end }}
  labels:
    app: gloo
    gloo: rbac
subjects:
- kind: ServiceAccount
  name: gateway
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: gloo
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: {{ include "gloo.roleKind" . }}
  name: gloo-resource-mutator{{ include "gloo.rbacNameSuffix" . }}
  apiGroup: rbac.authorization.k8s.io
---
kind: {{ include "gloo.roleKind" . }}Binding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gateway-resource-reader-binding{{ include "gloo.rbacNameSuffix" . }}
{{- if .Values.global.glooRbac.namespaced }}
  namespace: {{ .Release.Namespace }}
{{- end }}
  labels:
    app: gloo
    gloo: rbac
subjects:
- kind: ServiceAccount
  name: gateway
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: gloo # used to support gloo/gateway running in same pod
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: {{ include "gloo.roleKind" . }}
  name: gateway-resource-reader{{ include "gloo.rbacNameSuffix" . }}
  apiGroup: rbac.authorization.k8s.io
---
kind: {{ include "gloo.roleKind" . }}Binding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-graphqlapi-mutator-binding{{ include "gloo.rbacNameSuffix" . }}
  {{- if .Values.global.glooRbac.namespaced }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    app: gloo
    gloo: rbac
subjects:
{{- if .Values.discovery.enabled }}
  - kind: ServiceAccount
    name: discovery
    namespace: {{ .Release.Namespace }}
{{- else }}
  []
{{- end}}
roleRef:
  kind: {{ include "gloo.roleKind" . }}
  name: gloo-graphqlapi-mutator{{ include "gloo.rbacNameSuffix" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
{{- end -}}
