{{- if .Values.rbac.create }}

{{- if .Values.ingress.enabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-role-binding-ingress-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: gloo-role-ingress
  apiGroup: rbac.authorization.k8s.io

{{- end -}}

{{- end -}}
