{{- if .Values.global.glooRbac.create }}

{{- if .Values.settings.integrations.knative.enabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-role-binding-knative-{{ .Release.Namespace }}
  labels:
    app: gloo
    gloo: rbac
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: discovery
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: gloo
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: gloo-role-knative
  apiGroup: rbac.authorization.k8s.io
{{- end -}}

{{- end -}}
