{{- define "discovery.serviceAccountSpec"}}
{{- if .Values.discovery.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
{{- if .Values.discovery.serviceAccount.extraAnnotations }}
  annotations:
    {{- range $key, $value := .Values.discovery.serviceAccount.extraAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  labels:
    app: gloo
    gloo: discovery
  name: discovery
  namespace: {{ $.Release.Namespace }}
{{- if .Values.discovery.serviceAccount.disableAutomount }}
automountServiceAccountToken: false
{{ end }}
{{- end }}
{{- end }}

{{/* Render template with yaml overrides */}}
{{- $kubeResourceOverride := dict -}}
{{- if .Values.discovery.serviceAccount -}}
{{- $kubeResourceOverride = .Values.discovery.serviceAccount.kubeResourceOverride  -}}
{{- end -}}
{{- include "gloo.util.merge" (list . $kubeResourceOverride "discovery.serviceAccountSpec") -}}