{{- define "gateway.serviceSpec" }}
{{- if and .Values.gateway.enabled .Values.gateway.validation.enabled }}
{{- $statsConfig := coalesce .Values.gateway.deployment.stats .Values.global.glooStats -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    discovery.solo.io/function_discovery: disabled
    app: gloo
    gloo: gateway
  name: gateway
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    # this should map to projects/gateway/pkg/defaults.ValidationWebhookBindPort
    targetPort: 8443
{{- if and $statsConfig.enabled $statsConfig.serviceMonitorEnabled }}
  - name: http-monitoring
    port: 9091
{{- end }}
  selector:
    gloo: gateway
{{- end }} {{/* if .Values.gateway.enabled and .Values.gateway.validation.enabled */}}
{{- end }} {{/* define "gateway.serviceSpec" */}}

{{/* Render template with yaml overrides */}}
{{- $kubeResourceOverride := dict -}}
{{/* todo: once helm 3.5 becomes "normal" replace these with sprig dig function */}}
{{- if .Values.gateway.service -}}
{{- $kubeResourceOverride = .Values.gateway.service.kubeResourceOverride  -}}
{{- end -}}
{{- include "gloo.util.merge" (list . $kubeResourceOverride "gateway.serviceSpec") -}}