{{- if .Values.gateway.rolloutJob.enabled }}
{{- if .Values.global.glooRbac.create }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-resource-rollout
  namespace: {{ .Release.Namespace }}
  labels:
    app: gloo
    gloo: rbac
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0" # must be created before rollout job
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["gloo.solo.io"]
  resources: ["*"]
  verbs: ["get", "list", "create", "update", "patch"]
{{- end -}}{{/* if .Values.global.glooRbac.create */}}
{{- end }}{{/* if .Values.gateway.rolloutJob.enabled  */}}
