{{- if .Values.gateway.rolloutJob.enabled }}
{{- if .Values.global.glooRbac.create }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-resource-rollout
  namespace: {{ .Release.Namespace }}
  labels:
    app: gloo
    gloo: rbac
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["gloo.solo.io"]
  resources: ["*"]
  verbs: ["get", "list", "create", "update", "patch"]
# This permission is required by the oss rollout job in order to wait for the enterprise rollout job to finish first
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "delete"]
{{- end -}}{{/* if .Values.global.glooRbac.create */}}
{{- end }}{{/* if .Values.gateway.rolloutJob.enabled  */}}
