{{- if .Values.gateway.enabled }}
{{- if .Values.gateway.upgrade }}
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: gloo
    gloo: gateway
  name: gateway-conversion
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      labels:
        gloo: gateway
    spec:
      containers:
        - image: "{{ .Values.gateway.conversionJob.image.repository }}:{{ .Values.gateway.conversionJob.image.tag }}"
          imagePullPolicy: {{ .Values.gateway.conversionJob.image.pullPolicy }}
          name: gateway-conversion
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      restartPolicy: {{ .Values.gateway.conversionJob.restartPolicy }}
{{- end }}
{{- end }}