{{- if .Values.gateway.enabled }}
{{- range $name, $spec := .Values.gatewayProxies }}
{{- $svcName := default $name $spec.service.name }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gloo
    gloo: gateway-proxy
    gateway-proxy-id: {{ $name | kebabcase }}
  name: {{ $svcName | kebabcase }}
  namespace: {{ $.Release.Namespace }}
{{- if $spec.service.extraAnnotations }}
  annotations:
  {{- range $key, $value := $spec.service.extraAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
spec:
{{- if $spec.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ $spec.service.externalTrafficPolicy }}
{{- end }}
  ports:
  - port: {{ $spec.service.httpPort }}
    targetPort: {{ $spec.podTemplate.httpPort }}
    protocol: TCP
    name: http
  - port: {{ $spec.service.httpsPort }}
    targetPort: {{ $spec.podTemplate.httpsPort }}
    protocol: TCP
    name: https
  selector:
    gateway-proxy-id: {{ $name | kebabcase }}
    gateway-proxy: live
  type: {{ $spec.service.type }}
  {{- if and (eq $spec.service.type "ClusterIP") $spec.service.clusterIP }}
  clusterIP: {{ $spec.service.clusterIP }}
  {{- end }}
  {{- if and (eq $spec.service.type "LoadBalancer") $spec.service.loadBalancerIP }}
  loadBalancerIP: {{ $spec.service.loadBalancerIP }}
  {{- end }}
{{- end }}
{{ end }}
