{{- define "gatewayProxy.disruptionBudgetSpec"}}
{{- $name := (index . 1) }}
{{- $gatewaySpec := (index . 2) }}
{{- with (first .) }}
{{- $gatewayProxy := .Values.gatewayProxies.gatewayProxy -}}
{{- $spec := deepCopy $gatewaySpec | mergeOverwrite (deepCopy $gatewayProxy) -}}
{{- if $spec.kind.deployment}}
{{- if $spec.podDisruptionBudget }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $name | kebabcase }}-pdb
  namespace: {{ $spec.namespace | default .Release.Namespace }}
spec:
  {{- if $spec.podDisruptionBudget.minAvailable }}
  minAvailable: {{ $spec.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if $spec.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ $spec.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      gateway-proxy-id: {{ $name | kebabcase }}
{{- end }}
{{- end }}
{{- end }} {{/* with */}}
{{- end }} {{/* define gatewayProxy.deploymentSpec*/}}

{{- if .Values.gateway.enabled }}
{{- range $name, $gatewaySpec := .Values.gatewayProxies }}
{{/* Render each gatewayProxy template with it's yaml overrides */}}
{{- $kubeResourceOverride := dict -}}
{{- if $gatewaySpec.podDisruptionBudget -}}
{{- $kubeResourceOverride = $gatewaySpec.podDisruptionBudget.kubeResourceOverride }}
{{- end -}} {{/*if $gatewaySpec.podDisruptionBudget*/}}
{{- $ctx := (list $ $name $gatewaySpec)}}
---
{{- include "gloo.util.merge" (list $ctx $kubeResourceOverride "gatewayProxy.disruptionBudgetSpec") -}}
{{- end }}{{/* range $name, $gatewaySpec := .Values.gatewayProxies */}}
{{- end }}{{/* if .Values.gateway.enabled */}}