changelog:
  - type: NEW_FEATURE
    description: >
      Allow extauth to be deployed as both a standalone service and as a sidecar in
      the envoy pod simultaneously. We have added the field global.extensions.extAuth.standaloneDeployment
      to our helm chart and have deprecated (but not removed) the field global.extensions.extAuth.enabled.
      Setting both extAuth.envoySidecar and extAuth.standaloneDeployment to false should be equivalent
      to setting extAuth.enabled to false.
    issueLink: https://github.com/solo-io/gloo/issues/1537
    resolvesIssue: false
