kind: {{ include "gloo.roleKind" . }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.apiServer.service.name }}
  {{- if .Values.gloo.global.glooRbac.namespaced }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    app: gloo
    gloo: rbac
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "10"
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: [ "secrets"]
    verbs: ["get", "list", "watch", "create", "update"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "create"]
  - apiGroups: ["gloo.solo.io"]
    resources: ["artifacts", "settings", "upstreams", "upstreamgroups", "proxies", "secrets"]
    verbs: ["*"]
  - apiGroups: ["gateway.solo.io.v2"]
    resources: ["gateways"]
    verbs: ["*"]
  - apiGroups: ["gateway.solo.io"]
    resources: ["virtualservices"]
    verbs: ["*"]