apiVersion: apps/v1beta2
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "discovery.fullname" . }}
  labels:
    gloo: discovery
    chart: {{ template "gloo-ee.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.discovery.replicaCount }}
  selector:
    matchLabels:
      gloo: discovery
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        gloo: discovery
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: discovery
          image: "{{ .Values.discovery.image.repository }}:{{ .Values.discovery.image.tag }}"
          imagePullPolicy: {{ .Values.discovery.image.pullPolicy }}
          resources:
{{ toYaml .Values.discovery.resources | indent 12 }}
    {{- with .Values.discovery.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.discovery.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.discovery.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
