apiVersion: v1
description: Gloo Helm chart for Kubernetes
name: gloo
version: 0.5.0
home: https://gloo.solo.io/
icon: https://raw.githubusercontent.com/solo-io/gloo/master/docs/img/Gloo-01.png
sources:
  - https://github.com/solo-io/gloo