namespace:
  create: false
crds:
  create: true
k8s:
  clusterName: cluster.local

settings:
  create: true
  linkerd: false
  integrations:
    knative:
      enabled: true
      version: "0.8.0"
      proxy:
        image:
          repository: gloo-envoy-wrapper
        httpPort: 80
        httpsPort: 443
        replicas: 1
        stats: true

gateway:
  enabled: false

accessLogger:
  enabled: false

discovery:
  fdsMode: WHITELIST

ingress:
  # ingress proxy is disabled, but we still need the controller for knative
  enabled: false
  deployment:
    image:
      repository: ingress
    replicas: 1

global:
  image:
    registry: quay.io/solo-io
    pullPolicy: IfNotPresent
  glooRbac:
    create: true