# Default values for gloo-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ingress:
  type: LoadBalancer
  replicaCount: 1
  port: 8080
  securePort: 8443
  exposeAdminPort: false
  adminPort: 19000
  image: soloio/envoy
  imageTag: 0.4.2
  imagePullPolicy: IfNotPresent

control_plane:
  replicaCount: 1
  port: 8081
  image: soloio/control-plane
  imageTag: 0.4.2
  imagePullPolicy: IfNotPresent

#  addons
function_discovery:
  image: soloio/function-discovery
  imageTag: 0.4.2
  imagePullPolicy: IfNotPresent
  enable: true

kube_ingress_controller:
  image: soloio/kube-ingress-controller
  imageTag: 0.4.2
  imagePullPolicy: IfNotPresent
  enable: true

upstream_discovery:
  image: soloio/upstream-discovery
  imageTag: 0.4.2
  imagePullPolicy: IfNotPresent
  enable: true

opentracing:
  imagePullPolicy: IfNotPresent
  enable: false
  jaeger: jaegertracing/all-in-one:latest
  jaeger_host: jaeger.server
  jaeger_port: 9123
  status: disable

metrics:
  imagePullPolicy: IfNotPresent
  enable: false 
  service_monitor: false 
  prometheus_op: false 
  statsd_exporter: prom/statsd-exporter:latest
  statsd_host: statsd.server
  statsd_port: 9451
  status: disable 

prometheus:
  serviceMonitors:
  - name: "statsd-service-monitor"
    selector:
      matchLabels:
        app: statsd
    endpoints:
    - port: web
  
grafana:
  service:
    type: NodePort
  serverDashboardFiles: 
    gloo.json: |+
      {
        "dashboard":
          {
            "__inputs": [
              {
                "name": "DS_PROMETHEUS",
                "label": "prometheus",
                "description": "",
                "type": "datasource",
                "pluginId": "prometheus",
                "pluginName": "Prometheus"
              }
            ],
            "__requires": [
              {
                "type": "grafana",
                "id": "grafana",
                "name": "Grafana",
                "version": "5.0.0"
              },
              {
                "type": "panel",
                "id": "graph",
                "name": "Graph",
                "version": "5.0.0"
              },
              {
                "type": "datasource",
                "id": "prometheus",
                "name": "Prometheus",
                "version": "5.0.0"
              }
            ],
            "annotations": {
              "list": [
              {
                "builtIn": 1,
                "datasource": "-- Grafana --",
                "enable": true,
                "hide": true,
                "iconColor": "rgba(0, 211, 255, 1)",
                "name": "Annotations & Alerts",
                "type": "dashboard"
              }
            ]
          },
          "editable": true,
          "gnetId": null,
          "graphTooltip": 0,
          "id": null,
          "links": [],
          "panels": [
            {
              "aliasColors": {},
              "bars": false,
              "dashLength": 10,
              "dashes": false,
              "datasource": "${DS_PROMETHEUS}",
              "fill": 1,
              "gridPos": {
                "h": 9,
                "w": 12,
                "x": 0,
                "y": 0
              },
              "id": 2,
              "legend": {
                "avg": false,
                "current": false,
                "max": false,
                "min": false,
                "show": true,
                "total": false,
                "values": false
              },
              "lines": true,
              "linewidth": 1,
              "links": [],
              "nullPointMode": "null",
              "percentage": false,
              "pointradius": 5,
              "points": false,
              "renderer": "flot",
              "seriesOverrides": [],
              "spaceLength": 10,
              "stack": false,
              "steppedLine": false,
              "targets": [
                {
                  "expr": "sum(increase(envoy_listener______8080_http_http_downstream_rq_2xx[1m]))",
                  "format": "time_series",
                  "intervalFactor": 1,
                  "legendFormat": "2xx",
                  "refId": "A"
                },
                {
                  "expr": "sum(increase(envoy_listener______8080_http_http_downstream_rq_4xx[1m]))",
                  "format": "time_series",
                  "intervalFactor": 1,
                  "legendFormat": "4xx",
                  "refId": "B"
                },
                {
                  "expr": "sum(increase(envoy_listener______8080_http_http_downstream_rq_5xx[1m]))",
                  "format": "time_series",
                  "intervalFactor": 1,
                  "legendFormat": "5xx",
                  "refId": "C"
                }
              ],
              "thresholds": [],
              "timeFrom": null,
              "timeShift": null,
              "title": "Gloo Requests by Status",
              "tooltip": {
                "shared": true,
                "sort": 0,
                "value_type": "individual"
              },
              "type": "graph",
              "xaxis": {
                "buckets": null,
                "mode": "time",
                "name": null,
                "show": true,
                "values": []
              },
              "yaxes": [
                {
                  "format": "short",
                  "label": null,
                  "logBase": 1,
                  "max": null,
                  "min": "0",
                  "show": true
                },
                {
                  "format": "short",
                  "label": null,
                  "logBase": 1,
                  "max": null,
                  "min": null,
                  "show": true
                }
              ]
            }
          ],
          "schemaVersion": 16,
          "style": "dark",
          "tags": [
            "gloo"
          ],
          "templating": {
            "list": []
          },
          "time": {
            "from": "now-30m",
            "to": "now"
          },
          "timepicker": {
            "refresh_intervals": [
              "5s",
              "10s",
              "30s",
              "1m",
              "5m",
              "15m",
              "30m",
              "1h",
              "2h",
              "1d"
            ],
            "time_options": [
              "5m",
              "15m",
              "1h",
              "6h",
              "12h",
              "24h",
              "2d",
              "7d",
              "30d"
            ]
          },
          "timezone": "",
          "title": "Gloo Requests",
          "uid": "SMQRBwzmz",
          "version": 3
        },
        "inputs": [
          {
            "name": "DS_PROMETHEUS",
            "pluginId": "prometheus",
            "type": "datasource",
            "value": "prometheus"
          }
        ],
        "overwrite": true
      }
