namespace:
  create: false
rbac:
  create: true
crds:
  create: true
k8s:
  clusterName: cluster.local

settings:
  integrations:
    knative:
      enabled: true
      installKnative: true
      proxy:
        image:
          repository: quay.io/solo-io/gloo-envoy-wrapper
          pullPolicy: Always
        httpPort: 80
        httpsPort: 443
        replicas: 1

gateway:
  enabled: false

discovery:
  fdsMode: whitelist

ingress:
  # ingress proxy is disabled, but we still need the controller for knative
  enabled: false
  deployment:
    image:
      repository: quay.io/solo-io/ingress
      pullPolicy: Always
    replicas: 1
