namespace:
  create: false
rbac:
  create: true
crds:
  create: true
k8s:
  clusterName: cluster.local

settings:
  # if this is set to false, default settings will be created by pods upon boot
  create: false
  integrations:
    knative:
      enabled: false
  # namespaces that Gloo should watch. this includes watches set for pods, services, as well as CRD configuration objects
  watchNamespaces: []
  # the namespace that Gloo should write discovery data (Upstreams)
  writeNamespace: "gloo-system"

gloo:
  deployment:
    image:
      repository: quay.io/solo-io/gloo
      pullPolicy: Always
    xdsPort: 9977
    replicas: 1
    stats: true

discovery:
  deployment:
    image:
      repository: quay.io/solo-io/discovery
      pullPolicy: Always
    replicas: 1
    stats: true

gateway:
  enabled: true
  deployment:
    image:
      repository: quay.io/solo-io/gateway
      pullPolicy: Always
    replicas: 1
    stats: true

gatewayProxies:
  - name: gateway-proxy
    kind:
       deployment:
         replicas: 1
    podTemplate:
      image:
        repository: quay.io/solo-io/gloo-envoy-wrapper
        pullPolicy: Always
      stats: true
      httpPort: 8080
      httpsPort: 8443
    service:
      type: LoadBalancer
      # clusterIP: None
      httpPort: 80
      httpsPort: 443
    # Annotation example: setup ssl with aws cert when service.type is LoadBalancer
    # extraAnnotations:
    #   service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:EXAMPLE_CERT
    configMap:
      data:


ingress:
  enabled: false
