name: Setup KinD Cluster

description: The action that will seed a KinD cluster.

inputs:
  cluster-name:
    required: true
    description: The name of the KinD cluster
  kind-version:
    required: true
    description: The version of KinD
  kind-node-version:
    required: true
    description: The Node version used by KinD
  kubectl-version:
    required: true
    description: The version of Kubectl
  helm-version:
    required: true
    description: The version of Helm
  istio-version:
    required: true
    description: The version of Istio

runs:
  using: "composite"
  steps:
    - name: Install kind
      uses: helm/kind-action@v1.10.0
      with:
        install_only: true
        version: ${{ inputs.kind-version }}
    - uses: azure/setup-kubectl@v4
      id: kubectl
      with:
        version: ${{ inputs.kubectl-version }}
    - uses: azure/setup-helm@v4
      with:
        version: ${{ inputs.helm-version }}
    - name: Setup test env
      shell: bash
      env:
        CLUSTER_NAME: ${{ inputs.cluster-name }}
        CLUSTER_NODE_VERSION: ${{ inputs.kind-node-version }}
        ISTIO_VERSION: ${{ inputs.istio-version }}
      run: ./ci/kind/setup-kind.sh