name: Iron Mountain Escrow Deposit
on:
  release:
    types:
      - created
  workflow_dispatch:
  
jobs:
  deposit:
    name: Create Escrow Deposit
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure git for private modules
        env:
          # matches the GITHUB_ACTION secret used in the cloudbuild, but named CI_ADMIN_GITHUB_TOKEN here
          # because secrets.GITHUB_ACTION is reserved in github workflows
          TOKEN: ${{ secrets.CI_ADMIN_GITHUB_TOKEN }}
        run: git config --global url."https://soloio_bot:${TOKEN}@github.com".insteadOf "https://github.com"
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.5.2
      - name: Generate ExhibitB PDF and source tar
        env:
          TAGGED_VERSION: ${{ github.ref }}
        run: |
          make generate-escrow-pdf
      # LFTP was chosen because of the --env-password flag. Wanted to avoid having the password in any terminal history
      # or having it show up in any `ps` output
      - name: FTP-Deploy-Action
        uses: docker://mwienk/docker-lftp:latest
        env:
          LFTP_PASSWORD: ${{ secrets.IRON_MOUNTAIN_PASSWORD }}
        with:
          entrypoint: sh
          # This step is needed to avoid MITM attacks. The public key here has been verified (same output from
          # `ssh-keyscan -t rsa $host` from machines on separate networks) -- LFTP will fail to copy
          # the files over if the public key fails to validate with the server's private key. The public key may need
          # to be updated in the event the server key (private key) is rotated. In that event, it will be important to
          # validate that Iron Mountain didn't have a breach and verify the new public key before blindly updating it
          # here. Since this backup is all our closed source code and IP, DO NOT SKIP validation.
          args: |
            -c "echo '${{ var.ESCROWHOSTENTRY }}' >> known_hosts; lftp sftp://ftpipm.nccgroup.com:22 -u Solo.ioINC --env-password -e 'set sftp:connect-program ssh -o UserKnownHostsFile=known_hosts; mirror -R _gloo-ee-source/. 53312/; quit';"

