name: GGII Tests
on: pull_request

jobs:
  test_gloo_gateway2:
    name: Build and Test Gloo Gateway 2
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go 1.21
      uses: actions/setup-go@v4
      with:
        go-version: "1.21"
    - name: Build
      run: go build -v ./...
    - name: Install utils for env tests
      run: make install-go-tools
    - name: Test
      run: go test ./...

  conformance:
    name: Run Gateway api conformance tests
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go 1.21
      uses: actions/setup-go@v4
      with:
        go-version: "1.21"
    - name: Install kind
      uses: helm/kind-action@v1.5.0
      with:
        install_only: true
        version: v0.20.0
    - name: Setup Env in KinD
      run: make kind-create kind-helm
    - name: Test Conformance
      run: make conformance
