name: security-scan
on:
  release:
    types: [created]
jobs:
  release:
    name: Trivy Scan
    runs-on: "ubuntu-18.04"
    env:
      IMAGE_REPO: quay.io/solo-io
      SCAN_DIR: _output/scans
    strategy:
      matrix:
        image-type: [ 'access-logger', 'certgen', 'discovery', 'gateway', 'gloo', 'gloo-envoy-wrapper', 'ingress', 'sds' ]
    steps:
      - name: Cancel Previous Actions
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup - gcloud / gsutil
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GLOO_VULN_REPORTER }}
          project_id: solo-public
          export_default_credentials: true
      - name: Build an image from Dockerfile
        id: build-docker-image
        run: |
          VERSION=$(git describe --tags | cut -c 2-)
          TAGGED_VERSION=v$(echo $VERSION) make ${{ matrix.image-type }}-docker
          echo "::set-output name=VERSION::$(echo $VERSION)"
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_REPO }}/${{ matrix.image-type }}:${{ steps.build-docker-image.outputs.VERSION }}
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: trivy-results-${{ matrix.image-type }}.sarif
          severity: 'CRITICAL,HIGH'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: trivy-results-${{ matrix.image-type }}.sarif
      - name: Setup Gloo Docs Output
        run: |
          mkdir -p ${{ env.SCAN_DIR }}/${{ steps.build-docker-image.outputs.VERSION }}
      - name: Gloo Docs
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_REPO }}/${{ matrix.image-type }}:${{ steps.build-docker-image.outputs.VERSION }}
          format: 'template'
          template: '@hack/utils/security_scan_report/markdown.tpl'
          output: ${{ env.SCAN_DIR }}/${{ steps.build-docker-image.outputs.VERSION }}/${{ matrix.image-type }}_cve_report.docgen
          severity: 'CRITICAL,HIGH'
      - name: Publish Docs
        run: |
          VERSION=${{ steps.build-docker-image.outputs.VERSION }} SCAN_FILE=${{ matrix.image-type }}_cve_report.docgen make publish-security-scan
